package com.jonasgerdes.stoppelmap.preparation.entity

val marqueMappings = mapOf(
    "/zelte/alkoholfreies-zelt/" to "alkoholfreies-zelt",
    "/zelte/anton-linnemann/" to "anton-linnemann",
    "/zelte/banane/" to "banane",
    "/zelte/beckmanns-altdeutscher-biergarten/" to "beckmanns-altdeutscher-biergarten",
    "/zelte/bowle-royal-die-burg/" to "bowle-royal-die-burg",
    "/zelte/brackmann/" to "brackmann",
    "/zelte/charivari-drinkery/" to "charivari-drinkery",
    "/zelte/die-2-dinklager/" to "die-2-dinklager",
    "/zelte/die-flotte-das-partyschiff/" to "die-flotte-das-partyschiff",
    "/zelte/festzelt-bloemer/" to "festzelt-bloemer",
    "/zelte/festzelt-grieshop/" to "festzelt-grieshop",
    "/zelte/hogebacks-festzelt/" to "hogebacks-festzelt",
    "/zelte/kaponierzelt/" to "kaponierzelt",
    "/zelte/kombinat/" to "kombinat",
    "/zelte/kuehlings-niedersachsenhalle/" to "kuehlings-niedersachsenhalle",
    "/zelte/pickers-lutten-das-partyzelt/" to "pickers-lutten-das-partyzelt",
    "/zelte/schaefers-fetenscheune/" to "schaefers-fetenscheune",
    "/zelte/schirm-bar/" to "schirm-bar",
    "/zelte/sir-george/" to "sir-george",
    "/zelte/stoppel-schaenke/" to "stoppel-schaenke",
    "/zelte/stratmanns-echt-stoppelmarkt/" to "stratmanns-echt-stoppelmarkt",
    "/zelte/stratmanns-cafe-bierschaenke/" to "stratmanns-cafe-bierschaenke",
    "/zelte/wein-ellendorff/" to "wein-ellendorff",
    "/zelte/wunderbar-zelt/" to "wunderbar-zelt",
    "/zelte/zauberbar/" to "zauberbar",
    "/zelte/zum-alten-pferdestall/" to "zum-alten-pferdestall",
    "/zelte/zur-neuen-meyerei/" to "zur-neuen-meyerei",
)
