object DependencyVersions {
    const val gradlePlugin = "7.4.0-alpha07"
    const val kotlin = "1.7.0"
    const val kotlinxDatetime = "0.4.0"
    const val desugarSDK = "1.1.5"
    const val androidxCore = "1.7.0"
    const val androidxLifecycle = "2.6.0-alpha01"
    const val compose = "1.2.0"
    const val material3 = "1.0.0-alpha15"
    const val androidxActivityCompose = "1.5.1"
    const val androidxNavigation = "2.5.1"
    const val accompoanist = "0.24.13-rc"
    const val koin = "3.1.6"
    const val timber = "5.0.1"
    const val lottie = "5.2.0"
    const val mapBox = "10.7.0"
    const val sqldelight = "1.5.3"
    const val playServiceLocation = "20.0.0"
}
