object DependencyVersions {
    const val gradlePlugin = "7.4.0-alpha07"
    const val kotlin = "1.6.21"
    const val kotlinxDatetime = "0.4.0"
    const val desugarSDK = "1.1.5"
    const val androidxCore = "1.7.0"
    const val androidxRuntime = "2.4.0"
    const val compose = "1.2.0-rc02"
    const val material3 = "1.0.0-alpha12"
    const val androidxActivityCompose = "1.4.0"
    const val androidxNavigation = "2.5.0-rc01"
    const val koin = "3.1.6"
    const val timber = "5.0.1"
    const val lottie = "5.2.0"
}
