package com.jonasgerdes.stoppelmap.map.model

enum class MapIcon(val id: String) {
    Bar("bar"),
    CandyStall("candy_stall"),
    Expo("expo"),
    FoodStall("food_stall"),
    GameStall("game_stall"),
    Misc("misc"),
    Parking("parking"),
    Restaurant("restaurant"),
    Restroom("restroom"),
    Ride("ride"),
    SellerStall("seller_stall"),
    Entrance("entrance"),
    Station("station"),
    Platform("platform"),
    Taxi("taxi"),
    Kids("kids"),
    Wheelchair("wheelchair"),
    Plant("plant"),
    RedCross("red_cross"),
    Police("police"),
    Atm("atm"),
    WaterFountain("water_fountain"),
    TransitTickets("transit_tickets"),
    Bike("bike"),
}